title = "Example minosse configuration"

[minosse]
server = "0.0.0.0"
port = 8080
log = "debug"

  [minosse.connections]
  readTimeout = 30
  writeTimeout = 30
  maxConnections = 0

[zap]
mode = "development"