package main

const HTTP_POST_METHOD string = "POST"
const HTTP_GET_METHOD string = "GET"
const HTTP_NOT_FOUND string = "Not Found"
const HTTP_NOT_ALLOWED string = "Method Not Allowed"
const HTTP_OK string = "Ok"
const HTTP_NOT_FOUND_BODY string = "404 Not Found"
const HTTP_NOT_ALLOWED_BODY string = "405 Method Not Allowed"
const SPACE string = " "
const EOL string = "\n"
const HTTP_1_1 string = "HTTP/1.1"
const HEADER_CONTENT_TYPE string = "Content-Type"
const HEADER_CONTENT_LENGTH string = "Content-Length"
const HEADER_CACHE_CONTROL string = "Cache-Control"
const HEADER_CACHE_CONTROL_DEFAULT_VALUE string = "public, max-age=604800"
const HEADER_CONNECTION string = "Connection"
const HEADER_CONNECTION_CLOSE string = "close"
const HEADER_LAST_MODIFIED string = "Last-Modified"
const HEADER_DATE string = "Date"
const HEADER_SERVER string = "Server"
const HEADER_SERVER_VALUE string = "Minosse"
const GENERIC_ERROR_MESSAGE_LOG string = "Error reading request"
const CONNECTION_ERROR_MESSAGE_LOG string = "Error accepting new connection"
const HTTP_INTERNAL_SERVER_ERROR string = "500 Internal server error"
const TCP_PROTOCOL string = "TCP"
const TLS_PROTOCOL string = "TLS"
