title = "Example minosse configuration"

[minosse]
log = 0
port = 8080
server = "0.0.0.0"
webroot = "/Users/malattia/Workspace/golang/minosse"

[minosse.connections]
maxConnections = 500
readTimeout = 30
writeTimeout = 30

[zap]
mode = "development"
